add ensure_sufficient_test_coverage step

diff --git a/.github/workflows/automated-ci.yml b/.github/workflows/automated-ci.yml
--- a/.github/workflows/automated-ci.yml
+++ b/.github/workflows/automated-ci.yml
@@ -51,6 +51,32 @@ jobs:
           echo "cov single fail ${{ steps.pytester-cov.outputs.output-table }}"
           exit 1
 
+  ensure_sufficient_test_coverage:
+    runs-on: ubuntu-latest
+
+    steps:
+      - uses: actions/checkout@v3
+
+      - name: pytester-cov
+        id: pytester-cov
+        uses: programmingwithalex/pytester-cov@main
+        with:
+          pytest-root-dir: 'cdisc_rules_engine'
+          cov-threshold-single: 80
+          cov-threshold-total: 80
+
+      - name: Coverage single fail - exit
+        if: ${{ steps.pytester-cov.outputs.cov-threshold-single-fail == 'true' }}
+        run: |
+          echo "cov single fail ${{ steps.pytester-cov.outputs.output-table }}"
+          exit 1
+
+      - name: Coverage total fail - exit
+        if: ${{ steps.pytester-cov.outputs.cov-threshold-total-fail == 'true' }}
+        run: |
+          echo "cov single fail ${{ steps.pytester-cov.outputs.output-table }}"
+          exit 1  
+
   get_changed_files:
     runs-on: ubuntu-latest
     outputs:
