added pyreadstat unitttest

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -20,7 +20,17 @@ jobs:
           pip install setuptools wheel twine
           pip install -r requirements.txt
       - name: Build Binary
-        run: pyinstaller core.py --dist ./dist/output/ubuntu-latest --add-data=$pythonLocation/lib/python3.9/site-packages/xmlschema/schemas:xmlschema/schemas --add-data=resources/cache:resources/cache --add-data=resources/templates:resources/templates --add-data=resources/schema:resources/schema
+        run: pyinstaller core.py --dist ./dist/output/ubuntu-latest --hidden-import=pyreadstat._readstat_writer --add-data=$pythonLocation/lib/python3.9/site-packages/xmlschema/schemas:xmlschema/schemas --add-data=resources/cache:resources/cache --add-data=resources/templates:resources/templates --add-data=resources/schema:resources/schema
+      - name: Test Binary
+        run: |
+          cd dist/output/ubuntu-latest/core
+          chmod +x core
+          if ./core --help; then
+            echo "test passed"
+          else
+            echo "test failed"
+            exit 1
+          fi
       - name: Archive Artifacts
         uses: vimtor/action-zip@v1
         with:
@@ -50,7 +60,17 @@ jobs:
           pip install setuptools wheel twine
           pip install -r requirements.txt
       - name: Build Binary
-        run: pyinstaller core.py --dist ./dist/output/ubuntu-20-04 --add-data=$pythonLocation/lib/python3.9/site-packages/xmlschema/schemas:xmlschema/schemas --add-data=resources/cache:resources/cache --add-data=resources/templates:resources/templates --add-data=resources/schema:resources/schema
+        run: pyinstaller core.py --dist ./dist/output/ubuntu-20-04 --hidden-import=pyreadstat._readstat_writer --add-data=$pythonLocation/lib/python3.9/site-packages/xmlschema/schemas:xmlschema/schemas --add-data=resources/cache:resources/cache --add-data=resources/templates:resources/templates --add-data=resources/schema:resources/schema
+      - name: Test Binary
+        run: |
+          cd dist/output/ubuntu-20-04/core
+          chmod +x core
+          if ./core --help; then
+            echo "test passed"
+          else
+            echo "test failed"
+            exit 1
+          fi
       - name: Archive Artifacts
         uses: vimtor/action-zip@v1
         with:
@@ -80,7 +100,17 @@ jobs:
           pip install setuptools wheel twine
           pip install -r requirements.txt
       - name: Build Binary
-        run: pyinstaller core.py --dist ./dist/output/mac --add-data=$pythonLocation/lib/python3.9/site-packages/xmlschema/schemas:xmlschema/schemas --add-data=resources/cache:resources/cache --add-data=resources/templates:resources/templates --add-data=resources/schema:resources/schema
+        run: pyinstaller core.py --dist ./dist/output/mac --hidden-import=pyreadstat._readstat_writer --add-data=$pythonLocation/lib/python3.9/site-packages/xmlschema/schemas:xmlschema/schemas --add-data=resources/cache:resources/cache --add-data=resources/templates:resources/templates --add-data=resources/schema:resources/schema
+      - name: Test Binary
+        run: |
+          cd dist/output/mac/core
+          chmod +x core
+          if ./core --help; then
+            echo "test passed"
+          else
+            echo "test failed"
+            exit 1
+          fi
       - name: Archive Artifacts
         uses: vimtor/action-zip@v1
         with:
@@ -110,7 +140,16 @@ jobs:
           pip install setuptools wheel twine
           pip install -r requirements.txt
       - name: Build Binary
-        run: pyinstaller core.py --dist ./dist/output/windows --add-data="$env:pythonLocation\Lib\site-packages\xmlschema\schemas;xmlschema/schemas" --add-data="resources/cache;resources/cache" --add-data="resources/templates;resources/templates" --add-data="resources/schema;resources/schema"
+        run: pyinstaller core.py --dist ./dist/output/windows --hidden-import=pyreadstat._readstat_writer --add-data="$env:pythonLocation\Lib\site-packages\xmlschema\schemas;xmlschema/schemas" --add-data="resources/cache;resources/cache" --add-data="resources/templates;resources/templates" --add-data="resources/schema;resources/schema"
+      - name: Test Binary
+        run: |
+          cd dist/output/windows/core
+          if ./core.exe --help; then
+            echo "test passed"
+          else
+            echo "test failed"
+            exit 1
+          fi
       - name: Archive Windows Artifacts
         uses: vimtor/action-zip@v1
         with:
